spring.application.name=webapp
server.port=8080
server.servlet.context-path=/webapp

logging.level.com.neu.webapp.mapper=debug

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/webapp?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=Ap002245

mybatis-plus.mapper-locations=classpath:mapper/*.xml

mybatis-plus.type-aliases-package=com.neu.webapp.entity
